### PR TITLE
add ability to statically assign DMA channels

### PR DESCRIPTION
**Pull request by 2electricsheep**

### CODE REVIEW

**Comment by carlk3** [comment]
Please add some information about this new feature to the README.

Thanks

**Comment by carlk3** [comment]
Also, I think a better name the member name `static_dma_channels` would be `use_static_dma_channels` or maybe `use_static_DMA_channels` for consistency with `use_exclusive_DMA_IRQ_handler` .

**Review by 2electricsheep — COMMENTED** [review]
Thank you for your suggetions. I will do both. I think `use_static_dma_channels` would be better becuse the channels are listed as rx_dma and tx_dma.

**Review by 2electricsheep — COMMENTED** [review]
Also, I wanted to make sure you this wouldn't break other peoples existing usage code. My understanding is that it shouldn't, as long as their `spi_t` structs are intialized to zero. Which should be the case if they are globaly or staticly defined. What do you think?

**Comment by carlk3** [comment]
> Also, I wanted to make sure you this wouldn't break other peoples existing usage code. My understanding is that it shouldn't, as long as their `spi_t` structs are intialized to zero. Which should be the case if they are globaly or staticly defined. What do you think?

That should be fine. I already have a remark about that in the README:

* Generally, anything not specified will default to `0` or `false`. (This is the user's responsibility if using Dynamic Configuration, but in a Static Configuration [see [Static vs. Dynamic Configuration](#static-vs-dynamic-configuration)], the C runtime initializes static memory to 0.)

**Pull request merged**
